/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicLinkTokenRouteImport } from './routes/api/public/link.$token'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLinkTokenRoute = ApiPublicLinkTokenRouteImport.update({
  id: '/api/public/link/$token',
  path: '/api/public/link/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drive': typeof DriveRoute
  '/login': typeof LoginRoute
  '/api/public/link/$token': typeof ApiPublicLinkTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drive': typeof DriveRoute
  '/login': typeof LoginRoute
  '/api/public/link/$token': typeof ApiPublicLinkTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drive': typeof DriveRoute
  '/login': typeof LoginRoute
  '/api/public/link/$token': typeof ApiPublicLinkTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drive' | '/login' | '/api/public/link/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drive' | '/login' | '/api/public/link/$token'
  id: '__root__' | '/' | '/drive' | '/login' | '/api/public/link/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriveRoute: typeof DriveRoute
  LoginRoute: typeof LoginRoute
  ApiPublicLinkTokenRoute: typeof ApiPublicLinkTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/link/$token': {
      id: '/api/public/link/$token'
      path: '/api/public/link/$token'
      fullPath: '/api/public/link/$token'
      preLoaderRoute: typeof ApiPublicLinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriveRoute: DriveRoute,
  LoginRoute: LoginRoute,
  ApiPublicLinkTokenRoute: ApiPublicLinkTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
